"""init base

Revision ID: 56bfcf28c912
Revises: c7c0374fb534
Create Date: 2020-09-28 20:48:48.785959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bfcf28c912'
down_revision = 'c7c0374fb534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
